---
# tasks file for freeswitch-mw
#- name: Add FreeSwitch apt repository (1.4)
#  apt_repository: repo='deb http://files.freeswitch.org/repo/deb/debian/ wheezy main'

#- name: Add FreeSwitch Repo Signing key
#  apt_key: url=http://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub

#- name: Install FreeSwitch server
#  action: apt name=freeswitch-meta-vanilla update_cache=yes

- name: Add FreeSwitch 1.6 Repo Signing key (Debian)
  apt_key: url=http://files.freeswitch.org/repo/deb/freeswitch-1.6/freeswitch_archive_g0.pub
  when: (ansible_distribution == 'Debian')

- name: Add Freeswitch 1.6 apt repository (Debian 8/Jessie)
  apt_repository: repo='deb http://files.freeswitch.org/repo/deb/freeswitch-1.6/ jessie main'
  when: (ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie')

# Installation from sources
- name: Install FreeSwitch dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
   - freeswitch-video-deps-most
   - vim
   - fail2ban
  when: (ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie')

- name: Install FreeSwitch source code
  git: repo=https://freeswitch.org/stash/scm/fs/freeswitch.git
       dest={{freeswitch_sources_path}}
       version={{freeswitch_version}}
       update=yes
       accept_hostkey=yes

- name: bootstrap - take a coffee - it takes time --
  shell: ./bootstrap.sh -j chdir={{freeswitch_sources_path}}

- name: copy template modules file
  template: src={{ freeswitch_modules_template }} dest={{ freeswitch_sources_path }}/modules.conf force=yes

- name: Freeswitch configuration
  shell: ./{{freeswitch_configure_command}} chdir={{freeswitch_sources_path}}

- name: FreeSwitch make - another coffee ! --
  shell: make chdir={{freeswitch_sources_path}}

- name: FreeSwitch install
  shell: make install chdir={{freeswitch_sources_path}}

- name: FreeSwitch install sounds
  shell: make cd-sounds-install cd-moh-install chdir={{freeswitch_sources_path}}

- name: Add user "freeswitch"
  user: name={{freeswitch_owner}} group={{freeswitch_group}} home={{freeswitch_path}}

- name: Change ownership of FreeSwitch installation
  file: path={{freeswitch_path}} owner={{freeswitch_owner}} group={{freeswitch_group}} mode="ug=rwX,o=" state=directory recurse=yes

- name: Change ownership of FreeSwitch binary files
  file: path={{ freeswitch_path }}/bin/ owner={{freeswitch_owner}} group={{freeswitch_group}} mode="u=rwx,g=rx" state=directory recurse=yes

- name: Create /var/lib/freeswitch
  file: path=/var/lib/freeswitch owner={{freeswitch_owner}} group={{freeswitch_group}} mode="u=rwx,o=" state=directory recurse=yes

- name: Randomize default passwords
  shell:  /usr/bin/env perl {{ freeswitch_sources_path }}/scripts/perl/randomize-passwords.pl --files={{ freeswitch_path }}/conf/directory/default/1*.xml -D --vmlen=6

- name: systemd service
  template: src={{ freeswitch_init_template }} dest=/etc/systemd/system/freeswitch.service force=yes owner=root group=root mode=0644
  notify:
    - enable freeswitch
    - restart freeswitch

- name: cli link
  file: src={{ freeswitch_path }}/bin/fs_cli dest=/bin/fs_cli state=link

- name: log files management
  template: src={{ freeswicth_log_rotate_script }} dest=/etc/cron.daily/freeswitch_log_rotation mode="a+x"

- file: path=/var/log/freeswitch.log owner={{freeswitch_owner}} group={{freeswitch_group}} state=touch

# mod_fail2ban
# https://freeswitch.org/confluence/display/FREESWITCH/Fail2Ban
# https://freeswitch.org/confluence/display/FREESWITCH/mod_fail2ban
- name: Fetch fail2ban module source code
  git: repo=https://github.com/kurtabersold/freeswitch-mod_fail2ban.git
       dest={{freeswitch_sources_path}}/src/mod/applications/mod_fail2ban
       version=master
       update=yes
       accept_hostkey=yes

- name: fail2ban make
  make: chdir={{freeswitch_sources_path}}/src/mod/applications/mod_fail2ban

- name: fail2ban make install
  make: chdir={{freeswitch_sources_path}}/src/mod/applications/mod_fail2ban
        target=install

- name: fail2ban related config templates
  template: src={{item.src}} dest={{item.dest}} force=yes owner={{item.owner}} group={{item.group}} mode={{item.mode}}
  with_items:
    - { src: '{{ fail2ban_conf }}', dest: '{{ freeswitch_path }}/conf/autoload_configs/fail2ban.conf.xml', owner: '{{ freeswitch_owner }}', group: '{{ freeswitch_group }}', mode: '0660' }
    - { src: '{{ fail2ban_jail }}', dest: '/etc/fail2ban/jail.d/freeswitch.jail', owner: 'root', group: 'root', mode: '0644' }
    - { src: '{{ fail2ban_filter_fs }}', dest: '/etc/fail2ban/filter.d/freeswitch.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: '{{ fail2ban_filter_dos_fs }}', dest: '/etc/fail2ban/filter.d/freeswitch-dos.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: '../templates/modules/modules.conf.xml', dest: '{{ freeswitch_path }}/conf/autoload_configs/modules.conf.xml', owner: '{{ freeswitch_owner }}', group: '{{ freeswitch_group }}', mode: '0660' }
  notify:
    - restart freeswitch
    - restart fail2ban
